sudo: required
language: node_js

node_js:
  - 14.16.0 
  
cache:
  directories:
    - node_modules

branches:
  only:
  - writer #源码分支名称
    
before_install:
- wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb
- sudo dpkg -i ./pandoc-2.13-1-amd64.deb
- npm install -g hexo
- npm un hexo-renderer-marked --save
- npm install hexo-renderer-pandoc --save
    
before_script:
- git config user.name "Coldeye"
- git config user.email "948283368@qq.com"
- sed -i'' "s~https://github.com/Coldeye2020/coldeye2020.github.io.git~https://${GH_TOKEN}@github.com/coldeye2020/coldeye2020.github.io.git~" _config.yml

install:
- npm install
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo generate

after_success:
- hexo deploy
